// AUTO-GENERATED by scripts/add-portrait.ts — do not edit by hand.
// Run `npx tsx scripts/add-portrait.ts --rebuild` to refresh from disk.
//
// Maps slugified brawler name → filename (with extension) at
// /public/brawler-portraits/. BrawlerPortrait falls back to this file
// when the Brawlify CDN image fails to load. Map (not Set) so we can
// serve png/jpg/webp without the component having to guess the ext.

export const LOCAL_PORTRAITS = new Map<string, string>([
  ["damian", "damian.webp"],
  ["najia", "najia.png"],
  ["sirius", "sirius.png"],
  ["sirus", "sirus.png"],
]);
