// AUTO-GENERATED by scripts/add-portrait.ts — do not edit by hand.
// Run `npx tsx scripts/add-portrait.ts --rebuild` to refresh from disk.
//
// Lists slugified brawler names that have a manual portrait override
// at /public/brawler-portraits/{slug}.png. BrawlerPortrait falls back
// to the local file when the Brawlify CDN image fails to load.

export const LOCAL_PORTRAITS = new Set<string>([
  "Damian",
  "damian",
  "najia",
  "sirius",
  "sirus",
]);
