/**
 * scripts/add-portrait.ts
 *
 * Manual portrait wizard. For when Brawlify's CDN doesn't have a
 * brawler's image yet (typically new releases) and you want to drop
 * one in by hand instead of waiting for them to upload it.
 *
 * What it does:
 *   1. Slugifies the brawler name
 *   2. Copies a local file (--file) OR downloads a URL (--url) to
 *      /public/brawler-portraits/{slug}.png
 *   3. Regenerates /src/lib/local-portraits.ts so the BrawlerPortrait
 *      component knows to try the local override
 *
 * Usage:
 *   npx tsx scripts/add-portrait.ts Sirus --file ~/Downloads/sirus.png
 *   npx tsx scripts/add-portrait.ts Kaze  --url  https://example.com/kaze.png
 *   npx tsx scripts/add-portrait.ts                  # interactive
 *   npx tsx scripts/add-portrait.ts --list           # show overrides
 *   npx tsx scripts/add-portrait.ts --rebuild        # regen registry only
 *
 * No DB calls — pure filesystem. Safe to re-run.
 */

import * as fs from "fs/promises";
import * as path from "path";
import * as readline from "readline";
import { existsSync } from "fs";

const PORTRAITS_DIR = path.join(process.cwd(), "public", "brawler-portraits");
const REGISTRY_PATH = path.join(process.cwd(), "src", "lib", "local-portraits.ts");

// ──────────────────────────────────────────────────────────────────────────
// Terminal helpers (matches add-brawler.ts style)
// ──────────────────────────────────────────────────────────────────────────

const c = {
  reset: "\x1b[0m",
  bold: "\x1b[1m",
  dim: "\x1b[2m",
  red: "\x1b[31m",
  green: "\x1b[32m",
  yellow: "\x1b[33m",
  blue: "\x1b[34m",
  cyan: "\x1b[36m",
};

const ok = (m: string) => console.log(`  ${c.green}✓${c.reset} ${m}`);
const warn = (m: string) => console.log(`  ${c.yellow}⚠${c.reset} ${m}`);
const fail = (m: string) => console.log(`  ${c.red}✗${c.reset} ${m}`);
const info = (m: string) => console.log(`  ${c.dim}${m}${c.reset}`);
const header = (t: string) =>
  console.log(`\n${c.bold}${c.blue}${t}${c.reset}`);

function ask(prompt: string): Promise<string> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
  return new Promise((resolve) =>
    rl.question(`${c.cyan}?${c.reset} ${prompt} `, (a) => {
      rl.close();
      resolve(a.trim());
    })
  );
}

// ──────────────────────────────────────────────────────────────────────────
// Slug — must match BrawlerPortrait.slugify exactly
// ──────────────────────────────────────────────────────────────────────────

function slugify(name: string): string {
  return name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// ──────────────────────────────────────────────────────────────────────────
// Registry regen — reads the directory, writes the TS module
// ──────────────────────────────────────────────────────────────────────────

async function regenerateRegistry(): Promise<string[]> {
  await fs.mkdir(PORTRAITS_DIR, { recursive: true });
  const files = await fs.readdir(PORTRAITS_DIR);
  const slugs = files
    .filter((f) => /\.(png|jpg|jpeg|webp)$/i.test(f))
    .map((f) => f.replace(/\.[^.]+$/, ""))
    .sort();

  const body =
    slugs.length === 0
      ? ""
      : slugs.map((s) => `  ${JSON.stringify(s)},`).join("\n") + "\n";

  const out = `// AUTO-GENERATED by scripts/add-portrait.ts — do not edit by hand.
// Run \`npx tsx scripts/add-portrait.ts --rebuild\` to refresh from disk.
//
// Lists slugified brawler names that have a manual portrait override
// at /public/brawler-portraits/{slug}.png. BrawlerPortrait falls back
// to the local file when the Brawlify CDN image fails to load.

export const LOCAL_PORTRAITS = new Set<string>([
${body}]);
`;
  await fs.writeFile(REGISTRY_PATH, out);
  return slugs;
}

// ──────────────────────────────────────────────────────────────────────────
// Source resolution — local file or download
// ──────────────────────────────────────────────────────────────────────────

async function resolveSource(opts: {
  file?: string;
  url?: string;
}): Promise<{ buffer: Buffer; ext: string }> {
  if (opts.file) {
    const abs = path.resolve(opts.file);
    if (!existsSync(abs)) throw new Error(`File not found: ${abs}`);
    const buffer = await fs.readFile(abs);
    const ext = (path.extname(abs).slice(1) || "png").toLowerCase();
    if (!["png", "jpg", "jpeg", "webp"].includes(ext)) {
      throw new Error(`Unsupported extension ".${ext}" — use png/jpg/webp.`);
    }
    return { buffer, ext: ext === "jpeg" ? "jpg" : ext };
  }

  if (opts.url) {
    info(`Downloading ${opts.url}…`);
    const res = await fetch(opts.url);
    if (!res.ok) {
      throw new Error(`Download failed: ${res.status} ${res.statusText}`);
    }
    const ct = res.headers.get("content-type") || "";
    const buffer = Buffer.from(await res.arrayBuffer());
    let ext = "png";
    if (ct.includes("jpeg") || ct.includes("jpg")) ext = "jpg";
    else if (ct.includes("webp")) ext = "webp";
    else if (ct.includes("png")) ext = "png";
    else {
      // Trust the URL's extension as a last resort
      const urlExt = path.extname(new URL(opts.url).pathname).slice(1).toLowerCase();
      if (["png", "jpg", "jpeg", "webp"].includes(urlExt)) {
        ext = urlExt === "jpeg" ? "jpg" : urlExt;
      }
    }
    return { buffer, ext };
  }

  throw new Error("No source. Pass --file <path> or --url <url>.");
}

// ──────────────────────────────────────────────────────────────────────────
// Subcommands
// ──────────────────────────────────────────────────────────────────────────

async function cmdList() {
  header("Local portrait overrides");
  const slugs = await regenerateRegistry();
  if (slugs.length === 0) {
    info("None yet. Add one with:");
    info("  npx tsx scripts/add-portrait.ts <Name> --file <path>");
    return;
  }
  for (const s of slugs) ok(s);
  info(`\n${slugs.length} override${slugs.length === 1 ? "" : "s"} in ${PORTRAITS_DIR}`);
}

async function cmdRebuild() {
  header("Rebuild registry from disk");
  const slugs = await regenerateRegistry();
  ok(`Wrote ${REGISTRY_PATH} with ${slugs.length} entr${slugs.length === 1 ? "y" : "ies"}.`);
}

async function cmdAdd(name: string, opts: { file?: string; url?: string }) {
  header(`Add portrait for "${name}"`);

  const slug = slugify(name);
  if (!slug) {
    fail(`Name "${name}" produced an empty slug. Try a different name.`);
    process.exit(1);
  }
  info(`Slug: ${slug}`);

  // Interactive prompt if neither flag given
  if (!opts.file && !opts.url) {
    const answer = await ask("Local file path or URL? (leave empty to abort)");
    if (!answer) {
      info("Aborted.");
      return;
    }
    if (/^https?:\/\//i.test(answer)) opts.url = answer;
    else opts.file = answer;
  }

  const { buffer, ext } = await resolveSource(opts);
  const filename = `${slug}.${ext}`;
  const target = path.join(PORTRAITS_DIR, filename);

  await fs.mkdir(PORTRAITS_DIR, { recursive: true });

  // Clean up any other-extension version of this slug so we don't end
  // up with both shelly.png and shelly.webp racing each other.
  const existing = (await fs.readdir(PORTRAITS_DIR)).filter(
    (f) => f.replace(/\.[^.]+$/, "") === slug && f !== filename
  );
  for (const old of existing) {
    await fs.unlink(path.join(PORTRAITS_DIR, old));
    warn(`Removed stale ${old}`);
  }

  await fs.writeFile(target, buffer);
  ok(`Wrote ${path.relative(process.cwd(), target)} (${(buffer.length / 1024).toFixed(1)} KB)`);

  const slugs = await regenerateRegistry();
  ok(`Registry now has ${slugs.length} entr${slugs.length === 1 ? "y" : "ies"}.`);
  info(`Restart \`npm run dev\` if it doesn't pick up — Next caches /public.`);
}

// ──────────────────────────────────────────────────────────────────────────
// Main
// ──────────────────────────────────────────────────────────────────────────

function getFlag(argv: string[], flag: string): string | undefined {
  const i = argv.indexOf(flag);
  return i >= 0 ? argv[i + 1] : undefined;
}

async function main() {
  const argv = process.argv.slice(2);

  if (argv.includes("--list")) return cmdList();
  if (argv.includes("--rebuild")) return cmdRebuild();

  const file = getFlag(argv, "--file");
  const url = getFlag(argv, "--url");
  // First positional that isn't a flag value
  const flagValues = new Set([file, url].filter(Boolean) as string[]);
  let name = argv.find(
    (a) => !a.startsWith("--") && !flagValues.has(a)
  );

  if (!name) {
    name = await ask("Brawler name (e.g. Sirus):");
    if (!name) {
      fail("No name provided. Exiting.");
      process.exit(1);
    }
  }

  await cmdAdd(name, { file, url });
}

main().catch((e) => {
  console.error(`\n${c.red}Failed:${c.reset} ${e.message}`);
  process.exit(1);
});
